fix: agent jobs read access tokens the same way as main job
nrwl/ci pull request #25
Opened 2022-08-09 00:04 UTC by StalkAltan

The `nx-cloud-agents` workflow was not setting an env var for either `NX_CLOUD_ACCESS_TOKEN` or `NX_CLOUD_AUTH_TOKEN`. This can break DTE in cases where a user has a read-only token committed, but provides a read-write token through Github Secrets.

Also added `NX_BRANCH` so the main/agent jobs are in sync there as well.

2022-08-09 07:27 UTC, JamesHenry requested changes
Thanks @StalkAltan!

Please update the existing docs accordingly, the secrets will not flow through to the workflow automatically, the user must specify it

2022-08-10 02:56 UTC, StalkAltan commented
> Thanks @StalkAltan!
> 
> Please update the existing docs accordingly, the secrets will not flow through to the workflow automatically, the user must specify it

Good catch, made some adjustments there!

2022-08-10 12:58 UTC, JamesHenry commented
Thanks @StalkAltan, the final thing is to updated the version in the package.json to `0.6.1` to that the tagging workflow we have will create the new version after merge

2022-08-12 12:36 UTC, JamesHenry approved these changes

2022-08-12 12:36 UTC, merged

2022-08-12 12:36 UTC, JamesHenry commented
Thanks again @StalkAltan!