feat: added artifacts upload support
nrwl/ci pull request #41
Opened 2022-11-07 00:39 UTC by gperdomor

Closes #40

2022-11-07 01:32 UTC, JamesHenry requested changes
Thanks @gperdomor! Please add an integration-test workflow which proves that the artifacts are there and can be downloaded in a subsequent job. You can look at the existing integration-test workflows for inspiration

2022-11-07 01:48 UTC, gperdomor commented
@JamesHenry added... can you approve the workflow run?

2022-11-07 02:45 UTC, JamesHenry commented
@gperdomor please don’t force push to a PR that is actively being reviewed. It forces the reviewer to start from scratch on every commit

2022-11-07 03:08 UTC, gperdomor commented
@JamesHenry no more commits required, the pipeline already pass in my fork

2022-11-07 11:55 UTC, JamesHenry commented on README.md
> +    # NOTE: To download your artifact in anothe job you need to use the [download-artifact](https://github.com/actions/download-artifact) action
```suggestion
    # NOTE: To download your artifact in another job you need to use the [download-artifact](https://github.com/actions/download-artifact) action
```

2022-11-07 13:11 UTC, JamesHenry approved these changes

2022-11-07 13:38 UTC, meeroslav commented
Hey @gperdomor did you by any chance test if this solution works with multiline strings (passing multiple paths)?

We can extend this test:
```yaml
parallel-commands-on-agents: |
  npx nx run react-app:build
artifacts: ./integration-tests/npm/dist/
      
# ...
      
- run: node -e "if(fs.existsSync('dist/apps/react-app')) console.log('Artifacts are here...'); else { throw new Error('Artifacts do not exist!');}"      
```

to use wildcards and multiple artifact paths:

```yaml
parallel-commands-on-agents: |
  npx nx run react-app:build
  echo "hello world" > ./integration-tests/npm/dist/hello.txt
  echo "another file" > ./integration-tests/npm/dist/another.txt
artifacts: |
  ./integration-tests/npm/dist/apps/*
  ./integration-tests/npm/dist/*.txt
  
# ...
  
- run: node -e "if(fs.existsSync('dist/apps/react-app') && fs.existsSync('dist/hello.txt') && fs.existsSync('dist/another.txt')) console.log('Artifacts are here...'); else { throw new Error('Artifacts do not exist!');}"  
```

2022-11-07 13:57 UTC, gperdomor commented
@meeroslav honestly not, but the upload is handled by the upload-artifact action so should works

2022-11-07 14:11 UTC, LayZeeDK commented
I suggest generating test coverage reports, adding them to artifacts and verifying that they are available to the dependent job.

2022-11-07 15:08 UTC, gperdomor commented
@LayZeeDK @meeroslav done with dust and coverage folder :D

2022-11-07 15:15 UTC, LayZeeDK approved these changes
This will be helpful!

2022-11-07 15:16 UTC, LayZeeDK requested changes
Bump the version to indicate a feature addition and prepare a release.

2022-11-07 15:19 UTC, gperdomor commented
@LayZeeDK done :D

2022-11-08 11:35 UTC, SVendittelli reviewed
Could we also provide an input for the name of the artefact? See individual comments for suggested implementation.

2022-11-08 11:35 UTC, SVendittelli commented on README.md
> +    artifacts: ""
```yaml
    # [OPTIONAL] Provide the name of uploaded artifacts.
    #
    # NOTE: This input only has an effect if used with the `artifacts` input.
    # Default: "nx-main-artifacts"
    artifactsName: ""
```

2022-11-08 11:35 UTC, SVendittelli commented on .github/workflows/nx-cloud-main.yml
> +          name: nx-main-artifacts
```suggestion
          name: ${{ inputs.artifactsName }}
```

2022-11-08 11:35 UTC, SVendittelli commented on .github/workflows/nx-cloud-main.yml
> +        default: ""
```yaml
      artifactsName:
        required: false
        type: string
        default: nx-main-artifacts
```

2022-11-08 13:12 UTC, gperdomor commented
@SVendittelli done 👍🏻

2022-11-08 13:44 UTC, JamesHenry commented on .github/workflows/ci-integration-test-artifacts-multiple-folders.yml
> +      artifactsName: custom-artifacts-name
We use `dash-case` for all other inputs, please align i.e. `artifacts-name`.

Additionally, if there is agreement that `artifacts-name` is going to be supported, then I wold vote to change `artifacts` to `artifacts-path` to make it clearer what it corresponds to

2022-11-08 13:44 UTC, JamesHenry requested changes
See comment

2022-11-08 14:18 UTC, JamesHenry commented on README.md
> +    # NOTE: This input only has an effect if used with the `artifacts` input.
```suggestion
    # NOTE: This input only has an effect if used with the `artifacts-path` input.
```

2022-11-08 14:18 UTC, JamesHenry commented on README.md
> +    # will be `nx-main-artifacts`.
```suggestion
    # will be the value of the `artifacts-name` input.
```

2022-11-08 14:50 UTC, JamesHenry approved these changes
Thanks again @gperdomor!

2022-11-08 14:58 UTC, gperdomor commented
Happy to help :D...

2022-11-08 16:34 UTC, meeroslav commented
Thank you all for participating in this amazing new feature!

This will be super helpful for a lot of folks.

2022-11-08 16:34 UTC, merged

2022-11-09 08:40 UTC, bdebon commented
Guys, I'm so immensely happy and grateful that you implemented so quickly this thing I was asking for. And it's wonderful to see this PR with so many people interacting to deliver a bulletproof feature.
Thanks for all!