fix: lookup pnpm store path
nrwl/ci pull request #51
Opened 2022-12-21 09:49 UTC by cyrixmorten

I noticed that the "Install dependencies" step did not reuse any packages.

Now using `pnpm store path` as input for the cache directory. 

Example output before:
![image](https://user-images.githubusercontent.com/6650168/208874983-f418bfb4-395f-4681-93e9-709a8b9262ad.png)

Example output after:
![image](https://user-images.githubusercontent.com/6650168/208875068-2bfffeab-6f9c-4af5-85fe-ee407da2fe96.png)

2022-12-22 09:57 UTC, meeroslav requested changes
Looks good to me. Thanks!

Please bump the version in package.json and readme.md so this can be accessed via new version.

2023-01-02 18:18 UTC, cyrixmorten commented
No problem! :) will do so tomorrow

2023-01-03 08:08 UTC, meeroslav approved these changes

2023-01-04 09:29 UTC, cyrixmorten commented
@meeroslav I am not able to merge this PR. Just wanted to confirm that you aren't waiting for me to take action.

2023-01-04 10:59 UTC, meeroslav commented
Sorry, I was busy with other things. Thank you for the PR!

2023-01-04 10:59 UTC, merged